# Generated by Django 4.2.21 on 2025-05-19 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the blog source', max_length=255)),
                ('url', models.URLField(help_text='Main URL of the blog', max_length=500, unique=True)),
                ('rss_feed_url', models.URLField(help_text='URL of the RSS/Atom feed', max_length=500, unique=True)),
                ('last_fetched_time', models.DateTimeField(blank=True, help_text='when the feed waslast updated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Source',
                'verbose_name_plural': 'Blog Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the article', max_length=500)),
                ('link', models.URLField(help_text='Permanent link of the article', max_length=1000, unique=True)),
                ('publication_date', models.DateTimeField(blank=True, help_text='when the article was originally published', null=True)),
                ('content_snippet', models.TextField(blank=True, help_text='Content of the article')),
                ('fetched_date', models.DateTimeField(auto_now_add=True, help_text='When this article was fetched and stored')),
                ('guid', models.CharField(blank=True, db_index=True, help_text='globally unique identifier', max_length=500, null=True)),
                ('source', models.ForeignKey(help_text='the blog source of this article', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='aggregator.source')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-publication_date', '-fetched_date'],
            },
        ),
    ]
